### ISSUE TITLE
BNDInvocation.writeReturnValue<T>(_ value: T) could not find the type(Only in iOS10)

### ISSUE THREAD

**Issue by luziqin** [ReactiveKit/Bond#474] opened 2017-10-03 20:07 UTC
While i using the ObservableArray binding for tableview, there some issue just in ios10(the same code in ios11 is ok).Check out the frame for issue, i found the problem in "ProtocolProxy.swift", and the error is `fatal error: Bridging ObjC type BNDNSObjCValueType(rawValue: 105)` , the `BNDInvocation.writeReturnValue<T>(_ value: T)` could not find the type.
Is there someone have the same problem with me ? 
Any help?

**Comment by srdanrasic** [comment] 2017-10-05 07:09
I know where the problem is - thanks for reporting this. I'll fix it later today.

**Comment by tadasz** [comment] 2017-10-09 16:31
@scotteg could you give us a tip how to fix it, i want to test some feature on ios10 and it would be great to have a fix locally until new release. thanks!

**Comment by srdanrasic** [comment] 2017-10-09 18:51
I've just released 6.4.3 where this should be fixed. CocoaPods release coming in few minutes... Thanks for waiting :)

**Closed by srdanrasic** 2017-10-09 18:51 UTC
