### ISSUE TITLE
BAD_INSTRUCTION in dispose method when creating a CollectionViewCell

### ISSUE THREAD

**Issue by aregler** [ReactiveKit/Bond#441] opened 2017-07-20 09:24 UTC
Hello!
I am using AsyncDisplayKit for creating my CollectionViews.
So cells are basically created on a background thread.
When cells are created occasionally a EXC_BAD_ACCESS happens like here:

<img width="733" alt="screen shot 2017-07-20 at 11 14 02" src="https://user-images.githubusercontent.com/14072295/28409984-94a50204-6d3c-11e7-8479-ee5d461cd8cd.png">

<img width="498" alt="screen shot 2017-07-20 at 11 14 30" src="https://user-images.githubusercontent.com/14072295/28410014-ab7bb07c-6d3c-11e7-9480-83264f548279.png">

The function basically looks like this:

```  
 func collectionNode(_ collectionNode: ASCollectionNode, nodeBlockForItemAt indexPath: IndexPath) -> ASCellNodeBlock {
        return { [weak self] in
            guard let `self` = self else {
                fatalError(Constants.ErrorMessages.selfReference)
            }
            guard let cellType = self.viewModel?.cellType(at: indexPath) else {
                fatalError()
            }
            switch cellType { 
                ...
                case .item(let item):
                let node = PlayableEpisodeNode(withModel: item, insets: UIEdgeInsets(top: 16, left: 32, bottom: 16, right: 32))
                node.moreButton.reactive.tap.observeNext { [weak self] in
                    guard let `self` = self else {
                        fatalError(Constants.ErrorMessages.selfReference)
                    }
                    self.willShowDetailPage = true
                    self.output?.openItemDetailPage(id: item.identifier, urlStr: item.selfUrlString)
                }.dispose(in: self.bag)
                return node
            }
            }
```

if i change `node.moreButton.reactive.tap.observeNext {}.dispose(in: bag)` to `_ = node.moreButton.reactive.tap.observeNext {}` it works.
So i assume theres a problem within the dispose function.
Maybe its the same or a similar problem like  #416 .

**Comment by srdanrasic** [comment] 2017-07-21 08:02
Hey @aregler, I'm not sure if that's really the cause, but disposing the observation from a cell in `self.bag` is logically not good because cells can be reused and you want to dispose all observations in `prepareForReuse`.

Can you try disposing button observation in `collectionNode.bag`. I'm assuming collectionNode is equivalent to cell - I've never used AsyncDisplayKit.

You'll also want to dispose that bag then call is reused. Either override prepareForReuse on collectionNode if something like that exists or just before `switch cellType { ` line, do `collectionNode.bag.dispose()`.

Hope this solves to problem.

**Comment by aregler** [comment] 2017-07-22 12:09
Hi @srdanrasic. You were totally right. 😅
Thank you very much for all your work!

**Comment by aregler** [comment] 2017-07-22 15:07
Hey @srdanrasic. Unfortunately I have been glad too early 😆
The problem still exists, but at this point i am not sure if this should concern you.
I'll reopen this issue, but if you think it's too much related to ASDK then just close this issue.
Thanks anyway 😊

**Comment by srdanrasic** [comment] 2018-03-03 10:25
I was never able to reproduce something like that so I'll attribute this to AsyncDisplayKit and close the issue for now.

**Closed by srdanrasic** 2018-03-03 10:25 UTC
