### ISSUE TITLE
Index Out of Range using first(where: { }) and filter({ }) on MutableObservable2DArray

### ISSUE THREAD

**Issue by SeanRobinson159** [ReactiveKit/Bond#445] opened 2017-08-03 17:26 UTC
I have the following class setup:
```
class Session {
    private var items: MutableObservable2DArray<String, Item>
    var isUploading: Bool { return items.first(where: { $0.isUploading }) != nil }
   ...
}
```

```
class Item {
    var isUploading: Bool
    ...
}
```
When I try to access `session.isUploading` I get an index out of range error. I tried switching it to use a filter, like this:

`var isUploading: Bool { return !items.filter({ $0.isUploading }).isEmpty }`

I still get `fatal error: Index out of range`

Is this a bug? Or is it not an intended use of the `ObservableArray`

**Comment by srdanrasic** [comment] 2017-08-09 20:02
That's a bug! Thanks for reporting it, I'm looking into it.

**Comment by marclove** [comment] 2017-08-09 22:41
I'm encountering the same problem with `index(of:)`, though I suspect it's the same root cause: attempting to iterate over elements in sections using subscripts, starting with an index of 0, without first checking if the section is empty.

**Comment by srdanrasic** [comment] 2017-09-08 19:03
This bug has been fixed in one of the previous releases. Sorry for the late notification.

**Closed by srdanrasic** 2017-09-08 19:03 UTC
Labels: bug
