### ISSUE TITLE
`ProtocolProxy` only forwards Objective-C `selectors`. 

### ISSUE THREAD

**Issue by JettF** [ReactiveKit/Bond#320] opened 2016-10-27 18:04 UTC
**SET UP**
I have a `collectionView` that I am populating using Bond. The `forwardTo` property on the `collectionView`'s `bnd_dataSource` is set to my `viewController`. I want to move items in my `collectionView`, so on I implemented `collectionView:canMoveItemAt:` and `collectionView:moveItemAt:to:` on my `viewController`.

**PROBLEM**
I was unable to move the items in my `collectionView`.

**DISCUSSION**
After some debugging, I found that `ProtocolProxy` asks its `forwardTo` object if it responds to `collectionView:canMoveItemAtIndexPath:` and `collectionView:moveItemAtIndexPath:toIndexPath`. When I changed my method names to match these then my `viewController` was forwarded these calls properly.

Is there a way for the `ProtocolProxy` to ask its `forwardTo` object if it responds to the Swift versions of selectors as well as the Objective-C versions?

**Comment by srdanrasic** [comment] 2016-10-27 18:32
Looks like this is same as #311. I still haven't found the best solution to this...

**Comment by JettF** [comment] 2016-10-27 18:35
You are right! My apologies for opening an extra issue. Sadly, I don't have any suggestions yet, but I will give it some thought.

**Comment by srdanrasic** [comment] 2016-11-11 07:33
Closing as duplicate of #311

**Closed by srdanrasic** 2016-11-11 07:33 UTC
